### PR TITLE
support git's shallow clone

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Hi there,
I think you already know about shallow and cloning depth, I want to add this feature in gift, can help us save bandwith, diskspace, resource usage and time when the git repository is large, and we don't want to clone the whole repository.
Thanks!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@notatestuser is there any updates? Thanks.

**Comment by notatestuser** [comment]
Please do your rebase then let me know when that's done and I'll check over again. It is a breaking change and will require a major version release unless we want to have multiple `git.clone` signatures

**Comment by PeterDaveHello** [comment]
Already done!

**Comment by notatestuser** [comment]
Need to resolve conflicts in this branch for v1.0.0.

**Comment by PeterDaveHello** [comment]
working on it

**Comment by PeterDaveHello** [comment]
Updated, test passed.

**Comment by notatestuser** [comment]
Thanks!

**Comment by notatestuser** [comment]
Published in v0.7.0, which is (for intents and purposes) a v1.0.0 rc :+1:

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
