### PR TITLE
add git pull basic support

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
ping @notatestuser

**Comment by PeterDaveHello** [comment]
ping @notatestuser

**Comment by notatestuser** [comment]
Thanks but I'm not happy with the lack of test coverage on the argument sig of the new method. Also merely testing that an object is an instance of what is expected (`Repo` here) is never enough

**Comment by notatestuser** [comment]
OK for now. Thanks.

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
