### PR TITLE
support shallow clone a repo on a specific branch.

### PR DESCRIPTION
**Pull request by sparkleholic**
support `shallow clone` a repo on a specific branch.
`ex) git clone <git-url> --depth 1 --branch <name>`

### CODE REVIEW

**Comment by notatestuser** [comment]
Thanks for this!

**Comment by sparkleholic** [comment]
@notatestuser : Thanks for applying this. Can I ask you if you have any plan to publish new version into npm ?

**Comment by notatestuser** [comment]
I'll publish it shortly.

**Comment by notatestuser** [comment]
Published.

**Pull request merged**
